default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['db_host'] || 'postgres' %>
  user: <%= ENV['db_user'] || 'root' %>
  password: <%= ENV['db_password'] || 'root' %>

development:
  <<: *default
  database: lemoney_challenge_development

test:
  <<: *default
  database: lemoney_challenge_test

production:
  <<: *default
  database: lemoney_challenge_production
